Contant message processing via single __process() method (improves No…
millerf/django-channels-jsonrpc pull request #17
Opened 2017-04-26 08:35 UTC by soulhunter1987

…

Add tests for Django 1.11

2017-04-26 10:21 UTC, millerf requested changes

2017-04-26 10:21 UTC, millerf commented on channels_jsonrpc/jsonrpcconsumer.py
> -            logger.warning("The notification doesn't have a 'method'")
This is not covered anymore, instead of a warning it sends back a Exception with a null "id".
It needs to be modified

2017-04-26 10:21 UTC, millerf commented on channels_jsonrpc/jsonrpcconsumer.py
> -            logger.warning("The notification doesn't have a valid 'method'")
This is not covered anymore, instead of a warning it sends back a Exception with a null "id".
It needs to be modified

2017-04-26 10:21 UTC, millerf commented on channels_jsonrpc/jsonrpcconsumer.py
> -            logger.warning("The method '%s' of the notification cannot be found" % method_name)
This is not covered anymore, instead of a warning it sends back a Exception with a null "id".
It needs to be modified

2017-04-26 10:21 UTC, millerf commented on channels_jsonrpc/jsonrpcconsumer.py
> -                logger.warning("The method '%s' of the notification cannot be found" % method_name)
This is not covered anymore, instead of a warning it sends back a Exception with a null "id".
It needs to be modified

2017-04-26 10:21 UTC, millerf commented on channels_jsonrpc/jsonrpcconsumer.py
> -            logger.warning("The params '%s' are not valid" % params)
This is not covered anymore, instead of a warning it sends back a Exception with a null "id".
It needs to be modified

2017-04-26 10:36 UTC, soulhunter1987 commented
All changes you mentioned are intentional. Why should we raise Exceptions for calls, but log warnings for notifications? I think we should raise an Exception both for calls and notifications, and also log warnings for both of them, along with returning result for calls.
This is what is done now, except logging in case of Exception. But I plan to implement it in a separate task (ovarall improvements to logging).

2017-04-26 10:39 UTC, millerf commented
Exception will sends back a JSON-RPC frame, which shouldn’t happen for notifications… And also it looks like (I haven’t tested) the frame sent back has “null” as id…Which is incorrect... 



> On 26 Apr 2017, at 12:36, Dmitry <notifications@github.com> wrote:
> 
> All changes you mentioned are intentional. Why should we raise Exceptions for calls, but log warnings for notifications? I think we should raise an Exception both for calls and notifications, and also log warnings for both of them, along with returning result for calls.
> This is what is done now, except logging in case of Exception. But I plan to implement it in a separate task (ovarall improvements to logging).
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/millerf/django-channels-jsonrpc/pull/17#issuecomment-297345434>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAwQHnTgfJnZ5IArBVfwnAKPjX_mFHGsks5rzx4WgaJpZM4NIiN4>.
>

2017-04-26 10:42 UTC, soulhunter1987 commented
No, they won't. Because in methods "http_handler" and "raw_recieve" we already filter out notification responses (which may only occur in case of error, but allow us to take appropriate actions, for example set correct HTTP response code).

2017-04-27 08:39 UTC, millerf approved these changes

2017-04-27 08:39 UTC, merged